version: "3.8"

name: community_builds

services:
  db:
    image: postgres:latest
    container_name: community_builds_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community_builds_db
    ports:
      - "5656:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    container_name: community_builds_test_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community_builds_test_db
    ports:
      - "5657:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    # set the restart policy to "no" to prevent automatic restart outside test sessions
    restart: "no"

volumes:
  pgdata:
  test_pgdata:
