version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: community_builds_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community_builds_db
    ports:
      - "5656:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
